OPENAI_BASE_URL = "http://127.0.0.1:1234/v1"
OPENAI_API_KEY  = "lm-studio"

OPENAI_MODEL_TOPICS  = "qwen2.5:7b"
OPENAI_MODEL_SUMMARY = "qwen2.5:7b"
OPENAI_MODEL_MERGE   = "qwen2.5:7b"
CHUNK_CHARS = "6000"


